# Generated by Django 5.2.7 on 2025-10-14 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tedx_finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='agreement_proof',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='agreement',
            field=models.FileField(blank=True, null=True, upload_to='sponsors/'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Marketing', 'Marketing'), ('Logistics', 'Logistics'), ('Speakers', 'Speakers'), ('Venue', 'Venue'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='proofs/'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
