# Generated by Django 5.2.7 on 2025-10-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tedx_finance', '0003_historicalmanagementfund_historicalsponsor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Marketing', 'Marketing'), ('Logistics', 'Logistics'), ('Speakers', 'Speakers'), ('Venue', 'Venue'), ('Other', 'Other')], max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Planned budget amount', max_digits=10)),
                ('start_date', models.DateField(help_text='Budget period start')),
                ('end_date', models.DateField(help_text='Budget period end')),
            ],
        ),
    ]
