# Generated by Django 5.2.7 on 2026-01-03 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tedx_finance', '0006_budget_category_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tedx_finance.category', unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('success', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address', '-timestamp'], name='tedx_financ_ip_addr_312ccc_idx'), models.Index(fields=['username', '-timestamp'], name='tedx_financ_usernam_5143f8_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve_transaction', 'Approved Transaction'), ('reject_transaction', 'Rejected Transaction'), ('delete_transaction', 'Deleted Transaction'), ('create_fund', 'Created Fund'), ('update_fund', 'Updated Fund'), ('delete_fund', 'Deleted Fund'), ('create_category', 'Created Category'), ('update_category', 'Updated Category'), ('delete_category', 'Deleted Category'), ('export_data', 'Exported Data')], max_length=50)),
                ('object_type', models.CharField(max_length=50)),
                ('object_id', models.IntegerField()),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='tedx_financ_user_id_1f1868_idx'), models.Index(fields=['action', '-timestamp'], name='tedx_financ_action_417615_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('transaction_approved', 'Transaction Approved'), ('transaction_rejected', 'Transaction Rejected'), ('fund_created', 'Fund Created'), ('fund_low', 'Fund Running Low'), ('budget_exceeded', 'Budget Exceeded')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='tedx_financ_user_id_45a64d_idx'), models.Index(fields=['user', 'is_read'], name='tedx_financ_user_id_ce5f9d_idx')],
            },
        ),
    ]
